---
driver:
  name: azurerm
  subscription_id: '09f2ee05-2cb0-4996-a24e-b4d3083b0cbd'
  location: 'South Central US'
  machine_size: 'Standard_D2_v2'

provisioner:
  name: chef_zero
  product_name: chef
  product_version: 14.0.190
  client_rb:
    exit_status: :enabled
    environment: kitchen

verifier:
  name: inspec

platforms:
  - name: ubunutu1604
    driver_config:
      image_urn: Canonical:UbuntuServer:16.04-LTS:latest
    transport:
      ssh_key: ~/.ssh/id_kitchen-azurerm

suites:
  - name: demo_cookbook
    run_list:
      - recipe[demo_cookbook::default]
    environments_path: test/environments
    verifier:
      inspec_tests:
        - test/integration/default
